src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputAction.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java

Amends #1. That caused `WorkflowPluginTest.linearFlow` to fail sometimes. The reason was that the test as written restarted Jenkins and then immediately clicked the _Proceed_ link, without waiting for the agent to come back online. Since the flow execution does not resume until the agent is ready, which takes some time (tries to reconnect at intervals), the `proceed` REST API could easily hit the short (10s) timeout @svanoort talked me into against my best judgment. At that point not only did the initial click not work, but the `input` step could not be submitted even _after_ the build resumed (not that the test tried).
Applying the patch considered in #1, making the timeout be for each request individually, and increasing the timeout to reflect the fact that reality is messy and it is …

[JENKINS-37154] Timeout fixes

---

.gitignore
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help-submitter.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

submitter now allows multiple users/groups separated by ','
@reviewbybees please

[JENKINS-31425] should be able to specify multiple users or groups for the submitter of an input step

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help-submitterParameter.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

Add the submitterParameter property, used to record the submitter of an input step.
It will be treated like any other parameter on the input.  If the only value returned, will be returned directly. If other parameters, will be returned with the specified name.
Intended to fix https://issues.jenkins-ci.org/browse/JENKINS-31396

[FIXED JENKINS-31396] Add the submitterParameter property

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

Like the below step:
...
def x = input message: 'Approve or not', submitter: 'admin,dev', submitterParameter: 'my-approval'
echo x
...
When you click "Proceed" from the console output page, "x will be null in fact, but we expect x should be admin or dev.

Fix the returning null value when only submitterParameter and proceeding from console output page

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

[JENKINS-48998](https://issues.jenkins-ci.org/browse/JENKINS-48998)
For now I'm just granting to ADMINs - technically people with Item.CONFIGURE could bypass the Input (by Replay or changing the pipeline type).  It feels a bit wrong to encourage that though, if they're explicitly not supposed to be able to approve (by setting restricted submitters list for the InputStep). Admins on the other hand imply a high degree of trust implicitly.
@reviewbybees

Fix [JENKINS-48998] by ensuring admins can always approve

---

.mvn/extensions.xml
.mvn/maven.config
Jenkinsfile
pom.xml

See https://github.com/jenkinsci/incrementals-tools
This would be cool to be able to generate _Incrementals_ release on each `master` merge, or for PRs, like it should happen for this one already.
* RequireUpperBoundDeps fix induced by the parent pom bump
* Bump to Java 8 / Jenkins 2.60.3 as minimum version
(I had a local test failure on older core, and I do not think it still
makes sense to spend time even trying to understand why it fails on
Java 7 and Jenkins 1.642.4).

[JEP-305] Incrementalify

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help-submitter.html

Trivial improvement to make the step more user-friendly given people are used to put spaces after commas.

Trim submitter name before comparison

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java

While perusing the source tree, I noticed a number of deprecated methods:
- The documentation for [`ACL.impersonate(org.acegisecurity.Authentication, java.lang.Runnable)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#impersonate-org.acegisecurity.Authentication-java.lang.Runnable-) states: "use try with resources and [`as(Authentication)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#as-org.acegisecurity.Authentication-)".
- The documentation for [`Jenkins.getActiveInstance()`](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#getActiveInstance--) states: "This is a verbose historical alias for [`get()`](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#get--)."
Accordingly, I replaced any usages of `ACL.impersonate` with usages of try-with-resources …

Remove usages of deprecated APIs

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

Noticed in PCT and also observed locally:
```
java.lang.NullPointerException
at org.jenkinsci.plugins.workflow.support.steps.input.InputStepTest.test_submitter_parameter(InputStepTest.java:261)
```
I think the test found
```
[Pipeline] input
```
and proceeded, when the step was not yet fully initialized.
Amends #8.

Flake in InputStepTest.test_submitter_parameter

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

Bumps the [plugin parent POM](https://github.com/jenkinsci/plugin-pom) from 3.48 to 3.54.
See [the changelog](https://github.com/jenkinsci/plugin-pom/releases) and the full diff in [the compare view](https://github.com/jenkinsci/plugin-pom/compare/plugin-3.48...plugin-3.54).

Bump plugin parent POM

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

See [JENKINS-63516](https://issues.jenkins-ci.org/browse/JENKINS-63516). The fix in this PR is more or less copied from https://github.com/jenkinsci/pipeline-build-step-plugin/pull/46.
Both actual step usage and the snippet generator are fixed by this PR.

[JENKINS-63516] Make password parameters work with the input step in Jenkins 2.236+

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java

PR created to fix the following issue: https://issues.jenkins.io/browse/JENKINS-66798
Null check for the following:
`if (null != ud.getSymbol() && ud.getSymbol().equals("password")) {...}`

[JENKINS-66798] check null for ud.getSymbol()

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/ApproverAction.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputAction.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputSubmittedAction.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/Rejection.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

EOL JSR 305

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help.html

Changed "process" to "proceed" in the plugin documentation, since it is what appears in the UI.

Fix documentation typo for options available in stage view

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputAction.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

Export some data from InputAction to the HTTP API

---

README.md
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help-id.html

The documentation for the input step used ID when taking about the id field.
I have refactored all the references of ID to id
LINK: https://issues.jenkins.io/browse/JENKINS-69889

Describe identifiers more clearly in help and documentation

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java

Fixes a timing issue in #145 - whenever the `input` step was the last part of a `CpsThread`, it was possible that the thread would be removed from the thread group before we called `StepContext.get`, causing `CpsThreadGroup.doGet` to throw an exception.
https://github.com/jenkinsci/workflow-support-plugin/pull/252 would make this kind of change obsolete, but this change is minimal and cannot affect other plugins, so I think worth considering as a hotfix.  
I tested this manually using a test that failed reliably after https://github.com/jenkinsci/workflow-support-plugin/pull/252. With this change, it passes reliably.
```[tasklist]
```

Avoid "IOException: cannot find current thread" when submitting an input step that ends a `CpsThread`

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

Previous commit https://github.com/jenkinsci/pipeline-input-step-plugin/pull/159 (I cancelled that as had spotless issues :sweat:). I have actioned the feedback from that PR for inclusion in this PR.
There is a bug with the build result when a build is aborted. This seems to be an issue with the cause not being passed through to `doAbort()` [here](https://github.com/jenkinsci/pipeline-input-step-plugin/blob/b07d21da1afb043a5eeedec8d575a13c04773702/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java#L135-L147).
Reproduction steps to reproduce bug:
- make a pipeline job with the script being 'input 'proceed?', set it to abort previous builds
- run the job once (do not click on proceed, leave it running/waiting)
- run the job again
- Check the abort …

Fix incorrect abort cause

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepRestartTest.java

I have seen this test flaking (with timeout).
This shouldn't change the flakiness nature of the test, however if it does it should do it quicker and with a more meaningful message.

Better test result whenever InputStepRestartTest#interrupt fails

---

README.md
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help-submitter.html

[JENKINS-75384] updated user doc on input respond

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java

Fixes https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/920
In console:
It now allows inline approval for submitter and it correctly echoes it:
```groovy
node {
stage("Test Input") {
String approver = input(
message: "This an input test",
submitter: "lmoodley",
submitterParameter: "USER"
)    
println("${approver}")
}
}
```
Also tested in pipeline graph view and it works fine there too.

[JENKINS-40594] Handle submitterParameter in proceedEmpty
